Repository graphnet-team/graphnet, pull requests merged in 2022-08, with the labels that each got.

#238 Upgrade astropy, uninstall PyYAML
  docker/dockerfile
Labels: bug

#239 Mitigate soft_unicode error in docs by limiting MarkupSafe version
  setup.py
Labels: bug

#242 Update installation instructions
  README.md
Labels: documentation

#243 Close SQLite connection after construction to avoid problem with multiprocessing
  src/graphnet/data/dataset.py
  src/graphnet/data/parquet/parquet_dataset.py
  src/graphnet/data/sqlite/sqlite_dataset.py
Labels: bug

#246 Add default value of `loss_weight`
  src/graphnet/data/dataset.py
Labels: bug

#249 Optimise coarsening
  src/graphnet/components/pool.py
  src/graphnet/models/coarsening.py
  src/graphnet/models/detector/detector.py
  src/graphnet/models/graph_builders.py
Labels: enhancement

#250 Fix validate features
  src/graphnet/data/dataset.py
  src/graphnet/models/detector/detector.py
Labels: bug, high priority
